name: Mimosas and Nails

_editable_regions:
  image:
    url_src: true

_options:
  image: # Front matter field
    uploads_dir: 'images/:title'

sass:
  style: compact # possible values: nested expanded compact compressed
